name: CICD
on:
  workflow_dispatch:
env:
  ARTIFACT_NAME: "fbb_workflow_external-service-0.0.1-snapshot"
  WAR_NAME: "airnet-service.war"

jobs:
  build-app-service:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
        
    - name: "Checkout project"
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
    #       distribution: 'adopt'
           java-version: '8'

    - name: Cleaning target directory
      run: mvn clean 

    - name: Build with Maven 
      run: mvn clean package
      
    - name: Deploy to Azure Web App
    id: deploy-to-webapp
    uses: azure/webapps-deploy@v2
    with:
      app-name: 'app-thawatcd-az-asse-sbx-001'
      slot-name: 'Production'
     publish-profile: ${{ secrets.publishprofile}}
      package:  ${{ github.workspace }}/target/${{ env.WAR_NAME }}